baseURL: https://grafana.github.io/grizzly/
languageCode: en-us
defaultContentLanguage: en
title: Grizzly Docs
theme: cupper-hugo-theme

params:
  description: A utility for managing various observability resources with Jsonnet.
  homeMetaContent: Grizzly
  footer: Powered by [hugo](https://gohugo.io/), using the [cupper theme](https://themes.gohugo.io/cupper-hugo-theme/)
  dateFormat: Jan 1, 2021
  search: true
  logoAlt: Illustration of a Grizzly Bear Bust
  staticDir:
    - staticDir_override

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: What is Grizzly?
      weight: 2
      url: /what-is-grizzly
    - name: Getting Started
      url: /gettingstarted
      weight: 3
    - name: Available Systems
      identifier: systems
      url: /systems
      weight: 4
    - name: Grafana
      weight: 1
      url: /systems/grafana
      parent: systems
    - name: Prometheus
      weight: 2
      url: /systems/prometheus
      parent: systems
    - name: Grafana Synthetic Monitoring
      weight: 3
      url: /systems/synthetic-monitoring
      parent: systems
    - name: Usage
      url: /usage
      weight: 5
    - name: Workflows
      url: /workflows
      weight: 6
      identifier: workflows
    - name: Jsonnet
      url: /workflows/jsonnet
      weight: 1
      parent: workflows
    - name: Push/Pull
      url: /workflows/push-pull
      weight: 2
      parent: workflows
    - name: Listen
      url: /workflows/listen
      weight: 3
      parent: workflows
    - name: The Future
      url: /future
      weight: 7




markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
